name: Push and Pull

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  push_pull_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push and Pull
        run: echo "Success!"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Goodbye
        run: echo "Goodbye!"
        shell: bash
