name: Update Timestamp

on:
  schedule:
    - cron: "0 0 * * *" # run every day at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update timestamp
        run: |
          echo "Current timestamp: $(date -u)" > timestamp.txt

      - name: Commit and push
        run: |
          git config --global user.name 'owolfdev'
          git config --global user.email 'owolfdev@gmail.com'
          git add timestamp.txt
          git commit -m "Update timestamp"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/owolfdev/github-action-test.git
